# Generated by Django 3.1 on 2020-08-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20200826_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
