# Generated by Django 3.1 on 2020-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_variation_category'),
        ('carts', '0010_cartitems_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Variation'),
        ),
    ]
