# Generated by Django 3.1 on 2020-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200826_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('Two Sided', 'Two Sided'), ('Metal Stakes', 'Metal stakes')], default='size', max_length=120),
        ),
    ]
