# Generated by Django 3.1 on 2020-08-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_variation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('newsletter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('daily', models.BooleanField(default=True)),
            ],
        ),
    ]
