# Generated by Django 3.1 on 2020-09-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailmarketingsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailMarketingSignUp',
        ),
    ]
