# Generated by Django 3.1 on 2020-08-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name', 'slug')},
        ),
    ]
